# Generated by Django 4.0.4 on 2022-05-13 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calibre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc_calibre', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Objeto_tipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_de_objeto', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Objeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objeto_tipo_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='armas.objeto_tipo')),
            ],
        ),
        migrations.CreateModel(
            name='Municao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=64)),
                ('modelo', models.CharField(max_length=64)),
                ('valor_estimado', models.DecimalField(decimal_places=15, max_digits=30)),
                ('calibre_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='armas.calibre')),
            ],
        ),
        migrations.CreateModel(
            name='Arma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=64)),
                ('modelo', models.CharField(max_length=64)),
                ('valor_estimado', models.DecimalField(decimal_places=15, max_digits=30)),
                ('imagem', models.CharField(max_length=128)),
                ('calibre_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='armas.calibre')),
            ],
        ),
    ]
